# Generated by Django 5.2.5 on 2026-01-05 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(blank=True, max_length=20, null=True)),
                ('country_name', models.CharField(blank=True, max_length=225, null=True)),
                ('currency_code', models.CharField(blank=True, max_length=20, null=True)),
                ('languages', models.CharField(blank=True, max_length=225, null=True)),
                ('capital', models.CharField(blank=True, max_length=225, null=True)),
                ('iso2', models.CharField(db_index=True, max_length=20, unique=True)),
                ('iso3', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('iso_numeric', models.CharField(blank=True, max_length=20, null=True)),
                ('telephone_prefix', models.CharField(blank=True, max_length=20, null=True)),
                ('flag_png', models.URLField(blank=True, null=True)),
                ('flag_svg', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'countries',
                'ordering': ['country_name'],
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('code', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='utilities.country')),
            ],
            options={
                'db_table': 'zones',
            },
        ),
    ]
