# Generated by Django 5.2.5 on 2025-12-16 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='phone',
        ),
    ]
