# Generated by Django 5.2.5 on 2025-12-16 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0004_alter_guest_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='email',
        ),
    ]
