# Generated by Django 5.2.5 on 2026-01-06 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0005_remove_guest_contact_remove_guest_email'),
        ('utilities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='province',
            field=models.ForeignKey(default=3408, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='utilities.zone'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='nationality',
            field=models.ForeignKey(default=169, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='utilities.country'),
        ),
    ]
