# Generated by Django 5.2.5 on 2026-01-06 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_initial'),
        ('utilities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='address_line_1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='address_line_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='city',
            field=models.CharField(default='not-specified', max_length=100),
        ),
        migrations.AddField(
            model_name='employee',
            name='country',
            field=models.ForeignKey(default=169, on_delete=django.db.models.deletion.PROTECT, related_name='employee_addresses', to='utilities.country'),
        ),
        migrations.AddField(
            model_name='employee',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='province',
            field=models.ForeignKey(default=3408, on_delete=django.db.models.deletion.PROTECT, related_name='employee_addresses', to='utilities.zone'),
        ),
    ]
